version: 0.2

phases:
  install:
    commands:
      - echo npm install
      - npm install
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - git config user.name $USERNAME
      - git config user.password $TOKEN
      - npm run gh-pages
  post_build:
    commands:
      - echo Build completed on `date`
