version: 0.2

env:
  parameter-store:
    USERNAME: "GitHubUser"
    TOKEN: "GitHubToken"

phases:
  install:
    commands:
      - echo npm install
      - npm install
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - git --version
      - git config --global user.name $USERNAME && git config --global user.password $TOKEN && npm run gh-pages
  post_build:
    commands:
      - echo Build completed on `date`
