version: 0.2

env:
  parameter-store:
    USERNAME: "GitHubUser"
    TOKEN: "GitHubToken"

phases:
  install:
    commands:
      - echo npm install
      - npm install
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - git --version
      - sudo git config user.email $USERNAME
      - sudo git config user.name $USERNAME
      - sudo git config user.password $TOKEN
      - sudo npm run gh-pages
  post_build:
    commands:
      - echo Build completed on `date`
