version: 0.2

phases:
  install:
    commands:
      - git config --global credential.helper 'cache --timeout=3600'
      - git config --global user.name $USERNAME
      - git config --global user.password $TOKEN
      - echo npm install
      - npm install
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm run gh-pages
  post_build:
    commands:
      - echo Build completed on `date`
